name: overlay_support
description: proivder support for overlay, easy to build toast and internal notification
version: 1.0.4
author: YangBin <yangbinyhbn@gmail.com>
homepage: https://github.com/boyan01/overlay_support

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  provider: ^4.1.3
  flutter:
    sdk: flutter
  async: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: